### ISSUE TITLE
rubyバージョン指定なしのときのログ

### ISSUE THREAD

**Issue by waterlow** [waterlow/sinatra_app_runner#1]

**Comment by waterlow** [comment]
## 構築コマンドが `echo build` のとき

### buildログ

成功しているがbundle installはもちろん走っていない
```
01-03-2023 04:56:54 PM [AppRunner] Failed to deploy your application source code.
01-03-2023 04:49:38 PM [Build] Successfully tagged application-image:latest
01-03-2023 04:49:38 PM [Build] Successfully built f7e9b329e1b5
01-03-2023 04:49:38 PM [Build]  ---> f7e9b329e1b5
01-03-2023 04:49:38 PM [Build] Removing intermediate container dfbbcd99474f
01-03-2023 04:49:38 PM [Build]  ---> Running in dfbbcd99474f
01-03-2023 04:49:38 PM [Build] Step 5/5 : EXPOSE 4567
01-03-2023 04:49:38 PM [Build]  ---> 7ea309f17c16
01-03-2023 04:49:38 PM [Build] Removing intermediate container a66ecb761cf6
01-03-2023 04:49:38 PM [Build] build
01-03-2023 04:49:38 PM [Build]  ---> Running in a66ecb761cf6
01-03-2023 04:49:38 PM [Build] Step 4/5 : RUN echo build
01-03-2023 04:49:38 PM [Build]  ---> 81530d32495f
01-03-2023 04:49:38 PM [Build] Removing intermediate container f9b6d35c7cc0
01-03-2023 04:49:38 PM [Build]  ---> Running in f9b6d35c7cc0
01-03-2023 04:49:38 PM [Build] Step 3/5 : WORKDIR /app
01-03-2023 04:49:38 PM [Build]  ---> 06bd45eb218b
01-03-2023 04:49:38 PM [Build] Step 2/5 : COPY . /app
01-03-2023 04:49:38 PM [Build]  ---> 9f827ac9435b
01-03-2023 04:49:38 PM [Build] Status: Downloaded newer image for 335838599203.dkr.ecr.ap-northeast-1.amazonaws.com/awsfusionruntime-ruby31:3.1.3
01-03-2023 04:49:38 PM [Build] Digest: sha256:0cbf7db0dfd0015895d6a884f3e571076d40ddfaaaa6c9154dfaef35ee7ebfd4
01-03-2023 04:49:38 PM [Build] 9454b11ced8c: Pull complete
01-03-2023 04:49:38 PM [Build] 3d82502872e4: Pull complete
01-03-2023 04:49:38 PM [Build] a803d5fd9f1b: Pull complete
01-03-2023 04:49:38 PM [Build] 9454b11ced8c: Download complete
01-03-2023 04:49:38 PM [Build] 9454b11ced8c: Verifying Checksum
01-03-2023 04:49:38 PM [Build] a803d5fd9f1b: Download complete
01-03-2023 04:49:38 PM [Build] a803d5fd9f1b: Verifying Checksum
01-03-2023 04:49:38 PM [Build] 3d82502872e4: Download complete
01-03-2023 04:49:38 PM [Build] 9454b11ced8c: Pulling fs layer
01-03-2023 04:49:38 PM [Build] 3d82502872e4: Pulling fs layer
01-03-2023 04:49:38 PM [Build] a803d5fd9f1b: Pulling fs layer
01-03-2023 04:49:38 PM [Build] 3.1.3: Pulling from awsfusionruntime-ruby31
01-03-2023 04:49:38 PM [Build] Step 1/5 : FROM 335838599203.dkr.ecr.ap-northeast-1.amazonaws.com/awsfusionruntime-ruby31:3.1.3
01-03-2023 04:49:38 PM [Build] Sending build context to Docker daemon  7.168kB

01-03-2023 04:49:22 PM  
01-03-2023 04:49:22 PM [Build] build
01-03-2023 04:46:45 PM [AppRunner] Starting to build your application source code.
```

### アプリケーション起動ログ

gemがなくて起動に失敗する
```
01-03-2023 04:51:07 PM 	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
01-03-2023 04:51:07 PM 	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler.rb:161:in `setup'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/runtime.rb:18:in `setup'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/definition.rb:244:in `specs_for'
01-03-2023 04:51:07 PM 	from /usr/local/lib/ruby/3.1.0/bundler/definition.rb:187:in `specs'
01-03-2023 04:51:07 PM /usr/local/lib/ruby/3.1.0/bundler/definition.rb:507:in `materialize': Could not find puma-6.0.2, puma-6.0.2, puma-6.0.2, puma-6.0.2, puma-6.0.2, puma-6.0.2, puma-6.0.2, puma-6.0.2, sinatra-3.0.5, sinatra-3.0.5, sinatra-3.0.5, sinatra-3.0.5, sinatra-3.0.5, sinatra-3.0.5, sinatra-3.0.5, sinatra-3.0.5, nio4r-2.5.8, nio4r-2.5.8, nio4r-2.5.8, nio4r-2.5.8, nio4r-2.5.8, nio4r-2.5.8, nio4r-2.5.8, nio4r-2.5.8, mustermann-3.0.0, mustermann-3.0.0, mustermann-3.0.0, mustermann-3.0.0, mustermann-3.0.0, mustermann-3.0.0, mustermann-3.0.0, mustermann-3.0.0, rack-2.2.5, rack-2.2.5, rack-2.2.5, rack-2.2.5, rack-2.2.5, rack-2.2.5, rack-2.2.5, rack-2.2.5, rack-protection-3.0.5, rack-protection-3.0.5, rack-protection-3.0.5, rack-protection-3.0.5, rack-protection-3.0.5, rack-protection-3.0.5, rack-protection-3.0.5, rack-protection-3.0.5, tilt-2.0.11, tilt-2.0.11, tilt-2.0.11, tilt-2.0.11, tilt-2.0.11, tilt-2.0.11, tilt-2.0.11, tilt-2.0.11 in locally installed gems (Bundler::GemNotFound)
```

**Comment by waterlow** [comment]
## 構築コマンドが`bundle install`のとき

### 構築ログ
成功しているが、bundle installがdockerコンテナのbuild内外で1回ずつ計2回走っているように見える
```
01-03-2023 05:22:20 PM [AppRunner] Finished building your application source code.
01-03-2023 05:19:39 PM [Build] Successfully tagged application-image:latest
01-03-2023 05:19:39 PM [Build] Successfully built 6beee1c76d2e
01-03-2023 05:19:39 PM [Build]  ---> 6beee1c76d2e
01-03-2023 05:19:39 PM [Build] Removing intermediate container 3589d345e3e5
01-03-2023 05:19:39 PM [Build]  ---> Running in 3589d345e3e5
01-03-2023 05:19:39 PM [Build] Step 5/5 : EXPOSE 4567
01-03-2023 05:19:39 PM [Build]  ---> d22047e01dad
01-03-2023 05:19:39 PM [Build] Removing intermediate container eae9bd953d39
01-03-2023 05:19:39 PM [Build] Use `bundle info [gemname]` to see where a bundled gem is installed.
01-03-2023 05:19:39 PM [Build] Bundle complete! 2 Gemfile dependencies, 9 gems now installed.
01-03-2023 05:19:39 PM [Build] Installing puma 6.0.2 with native extensions
01-03-2023 05:19:39 PM [Build] Fetching puma 6.0.2
01-03-2023 05:19:39 PM [Build] Installing sinatra 3.0.5
01-03-2023 05:19:39 PM [Build] Fetching sinatra 3.0.5
01-03-2023 05:19:39 PM [Build] Installing rack-protection 3.0.5
01-03-2023 05:19:39 PM [Build] Fetching rack-protection 3.0.5
01-03-2023 05:19:39 PM [Build] Installing mustermann 3.0.0
01-03-2023 05:19:39 PM [Build] Fetching mustermann 3.0.0
01-03-2023 05:19:39 PM [Build] Installing tilt 2.0.11
01-03-2023 05:19:39 PM [Build] Fetching tilt 2.0.11
01-03-2023 05:19:39 PM [Build] Installing rack 2.2.5
01-03-2023 05:19:39 PM [Build] Installing nio4r 2.5.8 with native extensions
01-03-2023 05:19:39 PM [Build] Fetching rack 2.2.5
01-03-2023 05:19:39 PM [Build] Fetching nio4r 2.5.8
01-03-2023 05:19:39 PM [Build] Using ruby2_keywords 0.0.5
01-03-2023 05:19:39 PM [Build] Using bundler 2.3.26
01-03-2023 05:19:39 PM [Build] [0mFetching gem metadata from https://rubygems.org/....
01-03-2023 05:19:39 PM [Build] users on this machine.
01-03-2023 05:19:39 PM [Build] installing your bundle as root will break this application for all non-root
01-03-2023 05:19:39 PM [Build] [91mDon't run Bundler as root. Bundler can ask for sudo if it is needed, and
01-03-2023 05:19:39 PM [Build]  ---> Running in eae9bd953d39
01-03-2023 05:19:39 PM [Build] Step 4/5 : RUN bundle install
01-03-2023 05:19:39 PM [Build]  ---> 520b5fa1a147
01-03-2023 05:19:39 PM [Build] Removing intermediate container 544dc96413a3
01-03-2023 05:19:39 PM [Build]  ---> Running in 544dc96413a3
01-03-2023 05:19:39 PM [Build] Step 3/5 : WORKDIR /app
01-03-2023 05:19:39 PM [Build]  ---> a3362f35cb4d
01-03-2023 05:19:39 PM [Build] Step 2/5 : COPY . /app
01-03-2023 05:19:39 PM [Build]  ---> 9f827ac9435b
01-03-2023 05:19:39 PM [Build] Status: Downloaded newer image for 335838599203.dkr.ecr.ap-northeast-1.amazonaws.com/awsfusionruntime-ruby31:3.1.3
01-03-2023 05:19:39 PM [Build] Digest: sha256:0cbf7db0dfd0015895d6a884f3e571076d40ddfaaaa6c9154dfaef35ee7ebfd4
01-03-2023 05:19:39 PM [Build] 9454b11ced8c: Pull complete
01-03-2023 05:19:39 PM [Build] 3d82502872e4: Pull complete
01-03-2023 05:19:39 PM [Build] a803d5fd9f1b: Pull complete
01-03-2023 05:19:39 PM [Build] 9454b11ced8c: Download complete
01-03-2023 05:19:39 PM [Build] 9454b11ced8c: Verifying Checksum
01-03-2023 05:19:39 PM [Build] a803d5fd9f1b: Download complete
01-03-2023 05:19:39 PM [Build] 3d82502872e4: Download complete
01-03-2023 05:19:39 PM [Build] 3d82502872e4: Verifying Checksum
01-03-2023 05:19:39 PM [Build] 9454b11ced8c: Pulling fs layer
01-03-2023 05:19:39 PM [Build] 3d82502872e4: Pulling fs layer
01-03-2023 05:19:39 PM [Build] a803d5fd9f1b: Pulling fs layer
01-03-2023 05:19:39 PM [Build] 3.1.3: Pulling from awsfusionruntime-ruby31
01-03-2023 05:19:39 PM [Build] Step 1/5 : FROM 335838599203.dkr.ecr.ap-northeast-1.amazonaws.com/awsfusionruntime-ruby31:3.1.3
01-03-2023 05:19:39 PM [Build] Sending build context to Docker daemon  7.168kB

01-03-2023 05:19:21 PM  
01-03-2023 05:19:21 PM [Build] Use `bundle info [gemname]` to see where a bundled gem is installed.
01-03-2023 05:19:21 PM [Build] Bundle complete! 2 Gemfile dependencies, 9 gems now installed.
01-03-2023 05:19:21 PM [Build] Installing puma 6.0.2 with native extensions
01-03-2023 05:19:21 PM [Build] Fetching puma 6.0.2
01-03-2023 05:19:21 PM [Build] Installing sinatra 3.0.5
01-03-2023 05:19:21 PM [Build] Fetching sinatra 3.0.5
01-03-2023 05:19:21 PM [Build] Installing rack-protection 3.0.5
01-03-2023 05:19:21 PM [Build] Fetching rack-protection 3.0.5
01-03-2023 05:19:21 PM [Build] Installing mustermann 3.0.0
01-03-2023 05:19:21 PM [Build] Fetching mustermann 3.0.0
01-03-2023 05:19:21 PM [Build] Installing tilt 2.0.11
01-03-2023 05:19:21 PM [Build] Fetching tilt 2.0.11
01-03-2023 05:19:21 PM [Build] Installing rack 2.2.5
01-03-2023 05:19:21 PM [Build] Installing nio4r 2.5.8 with native extensions
01-03-2023 05:19:21 PM [Build] Fetching rack 2.2.5
01-03-2023 05:19:21 PM [Build] Fetching nio4r 2.5.8
01-03-2023 05:19:21 PM [Build] Using ruby2_keywords 0.0.5
01-03-2023 05:19:21 PM [Build] Using bundler 2.3.26
01-03-2023 05:19:21 PM [Build] Resolving dependencies...
01-03-2023 05:19:21 PM [Build] Fetching gem metadata from https://rubygems.org/....
01-03-2023 05:19:21 PM [Build] users on this machine.
01-03-2023 05:19:21 PM [Build] installing your bundle as root will break this application for all non-root
01-03-2023 05:19:21 PM [Build] Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
01-03-2023 05:19:21 PM [Build] Installing bundler 2.3.26
01-03-2023 05:19:21 PM [Build] Fetching bundler 2.3.26
01-03-2023 05:19:21 PM [Build] Fetching gem metadata from https://rubygems.org/.
01-03-2023 05:19:21 PM [Build] Bundler 2.3.7 is running, but your lockfile was generated with 2.3.26. Installing Bundler 2.3.26 and restarting using that version.
01-03-2023 05:19:21 PM [Build] users on this machine.
01-03-2023 05:19:21 PM [Build] installing your bundle as root will break this application for all non-root
01-03-2023 05:19:21 PM [Build] Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
01-03-2023 05:16:30 PM [AppRunner] Starting to build your application source code.
```

### アプリケーションログ
```
01-03-2023 05:20:58 PM Use Ctrl-C to stop
01-03-2023 05:20:58 PM * Listening on http://0.0.0.0:4567
01-03-2023 05:20:58 PM *          PID: 1
01-03-2023 05:20:58 PM *  Environment: development
01-03-2023 05:20:58 PM *  Max threads: 5
01-03-2023 05:20:58 PM *  Min threads: 0
01-03-2023 05:20:58 PM * Puma version: 6.0.2 (ruby 3.1.3-p185) ("Sunflower")
01-03-2023 05:20:58 PM Puma starting in single mode...
01-03-2023 05:20:58 PM == Sinatra (v3.0.4) has taken the stage on 4567 for development with backup from Puma
```

**Comment by waterlow** [comment]
## 構築コマンド`bundle install;`のとき

build
```
01-03-2023 05:39:51 PM [AppRunner] Finished building your application source code.
01-03-2023 05:36:23 PM  
01-03-2023 05:36:22 PM [Build] Successfully tagged application-image:latest
01-03-2023 05:36:22 PM [Build] Successfully built de3e5223f8a9
01-03-2023 05:36:22 PM [Build]  ---> de3e5223f8a9
01-03-2023 05:36:22 PM [Build] Removing intermediate container 88f584feda47
01-03-2023 05:36:22 PM [Build]  ---> Running in 88f584feda47
01-03-2023 05:36:22 PM [Build] Step 5/5 : EXPOSE 4567
01-03-2023 05:36:22 PM [Build]  ---> 0b89b37518c6
01-03-2023 05:36:22 PM [Build] Removing intermediate container 91f7d352814b
01-03-2023 05:36:22 PM [Build] Use `bundle info [gemname]` to see where a bundled gem is installed.
01-03-2023 05:36:22 PM [Build] Bundle complete! 2 Gemfile dependencies, 9 gems now installed.
01-03-2023 05:36:22 PM [Build] Installing puma 6.0.2 with native extensions
01-03-2023 05:36:22 PM [Build] Fetching puma 6.0.2
01-03-2023 05:36:22 PM [Build] Installing sinatra 3.0.5
01-03-2023 05:36:22 PM [Build] Fetching sinatra 3.0.5
01-03-2023 05:36:22 PM [Build] Installing rack-protection 3.0.5
01-03-2023 05:36:22 PM [Build] Fetching rack-protection 3.0.5
01-03-2023 05:36:22 PM [Build] Installing mustermann 3.0.0
01-03-2023 05:36:22 PM [Build] Fetching mustermann 3.0.0
01-03-2023 05:36:22 PM [Build] Installing tilt 2.0.11
01-03-2023 05:36:22 PM [Build] Fetching tilt 2.0.11
01-03-2023 05:36:22 PM [Build] Installing rack 2.2.5
01-03-2023 05:36:22 PM [Build] Installing nio4r 2.5.8 with native extensions
01-03-2023 05:36:22 PM [Build] Fetching rack 2.2.5
01-03-2023 05:36:22 PM [Build] Fetching nio4r 2.5.8
01-03-2023 05:36:22 PM [Build] Using ruby2_keywords 0.0.5
01-03-2023 05:36:22 PM [Build] Using bundler 2.3.26
01-03-2023 05:36:22 PM [Build] [0mFetching gem metadata from https://rubygems.org/....
01-03-2023 05:36:22 PM [Build] users on this machine.
01-03-2023 05:36:22 PM [Build] installing your bundle as root will break this application for all non-root
01-03-2023 05:36:22 PM [Build] [91mDon't run Bundler as root. Bundler can ask for sudo if it is needed, and
01-03-2023 05:36:22 PM [Build]  ---> Running in 91f7d352814b
01-03-2023 05:36:22 PM [Build] Step 4/5 : RUN bundle install;
01-03-2023 05:36:22 PM [Build]  ---> 2ed15fa3fdd5
01-03-2023 05:36:22 PM [Build] Removing intermediate container 1d005ff1e8a8
01-03-2023 05:36:22 PM [Build]  ---> Running in 1d005ff1e8a8
01-03-2023 05:36:22 PM [Build] Step 3/5 : WORKDIR /app
01-03-2023 05:36:22 PM [Build]  ---> cf5f778cc5b8
01-03-2023 05:36:22 PM [Build] Step 2/5 : COPY . /app
01-03-2023 05:36:22 PM [Build]  ---> 9f827ac9435b
01-03-2023 05:36:22 PM [Build] Status: Downloaded newer image for 335838599203.dkr.ecr.ap-northeast-1.amazonaws.com/awsfusionruntime-ruby31:3.1.3
01-03-2023 05:36:22 PM [Build] Digest: sha256:0cbf7db0dfd0015895d6a884f3e571076d40ddfaaaa6c9154dfaef35ee7ebfd4
01-03-2023 05:36:22 PM [Build] 9454b11ced8c: Pull complete
01-03-2023 05:36:22 PM [Build] 3d82502872e4: Pull complete
01-03-2023 05:36:22 PM [Build] a803d5fd9f1b: Pull complete
01-03-2023 05:36:22 PM [Build] 9454b11ced8c: Download complete
01-03-2023 05:36:22 PM [Build] 9454b11ced8c: Verifying Checksum
01-03-2023 05:36:22 PM [Build] a803d5fd9f1b: Download complete
01-03-2023 05:36:22 PM [Build] a803d5fd9f1b: Verifying Checksum
01-03-2023 05:36:22 PM [Build] 3d82502872e4: Download complete
01-03-2023 05:36:22 PM [Build] 3d82502872e4: Verifying Checksum
01-03-2023 05:36:22 PM [Build] 9454b11ced8c: Pulling fs layer
01-03-2023 05:36:22 PM [Build] 3d82502872e4: Pulling fs layer
01-03-2023 05:36:22 PM [Build] a803d5fd9f1b: Pulling fs layer
01-03-2023 05:36:22 PM [Build] 3.1.3: Pulling from awsfusionruntime-ruby31
01-03-2023 05:36:22 PM [Build] Step 1/5 : FROM 335838599203.dkr.ecr.ap-northeast-1.amazonaws.com/awsfusionruntime-ruby31:3.1.3
01-03-2023 05:36:22 PM [Build] Sending build context to Docker daemon  7.168kB

01-03-2023 05:33:08 PM [AppRunner] Starting to build your application source code.
```

app start
```
01-03-2023 05:38:32 PM Use Ctrl-C to stop
01-03-2023 05:38:32 PM * Listening on http://0.0.0.0:4567
01-03-2023 05:38:32 PM *          PID: 1
01-03-2023 05:38:32 PM *  Environment: development
01-03-2023 05:38:32 PM *  Max threads: 5
01-03-2023 05:38:32 PM *  Min threads: 0
01-03-2023 05:38:32 PM * Puma version: 6.0.2 (ruby 3.1.3-p185) ("Sunflower")
01-03-2023 05:38:32 PM Puma starting in single mode...
01-03-2023 05:38:32 PM == Sinatra (v3.0.4) has taken the stage on 4567 for development with backup from Puma
```
